### PR TITLE
Allow deployments with artifacts from artifact manager

### PR DESCRIPTION
**Pull request by twolfart**
Currently the deployment from a freshly checked out project does not work, at least config-definition needs to be built locally.

### CODE REVIEW

**Comment by stefanseifert** [comment]
can you give more information about the use case you try to solve?
the build-deploy script automatically does an install (incl. compile) step as part of the "build" before executing the "deploy".
only if the "deploy" step is called on it's own the build step is omitted, but this is by intention to speed up things because it can be used to executed build only once and then execute deploy multiple times e.g. on different instances.

**Comment by twolfart** [comment]
My use case is:
* script is used in a CI, targeting a test environment sharing the local settings
* deploying is enough, because the required project artifacts have already been built and are available in an artifact manager

**Comment by stefanseifert** [comment]
i think from a CI process you should not use the convenience script "build-deploy.sh", but execute the desired maven commands directly. than you have full control and are not affected by future changes of build-deploy.sh. the main purpose of build-deploy.sh is to have a convenient command line interface for the developers locally.

**Comment by twolfart** [comment]
The idea here is to do the same as the developers. Falling back to Maven commands may also miss future extensions.
Anyways, adding or not adding compile, both is fine for me - it's not really a hard issue on my side (especially since it's the archetype here).
Feel free to close the PR if "compile" is not intended.

**Comment by stefanseifert** [comment]
closing, it's not the intention of this script to be used in CI/CD

**Pull request closed without merging**
